name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Cleanup Workspace
      - name: Cleanup Workspace
        run: |
          echo "Cleaning up workspace..."
          rm -rf $HOME/.cache
          rm -rf $GITHUB_WORKSPACE/*

